[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#0B0B16"
secondaryBackgroundColor = "#14141F"
textColor = "#DEDEEA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true
